logging.level.org.springframework.cloud.gateway.filter: trace

server:
  port: 8282

spring:
  application:
    name: gateway
  cloud:
    gateway:
      predicate:
        cloud-foundry-route-service:
          enabled: false
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - predicates:
            - Path=/h2c
          uri: http://127.0.0.1:8088
        - predicates:
            - Path=/http
          uri: http://127.0.0.1:8089
