logging:
  level:
    org.springframework.cloud.gateway.filter: trace

server:
  port: 8282

spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        register: false
    loadbalancer:
      cache:
        ttl: 30s
    gateway:
      mvc:
        http-client:
          connect-timeout: 1s
          read-timeout: 5s
        routes:
          - id: my-foo
            predicates:
              - Path=/foo
            uri: lb://foo
