logging.level.org.springframework.cloud.gateway.filter: trace

server:
  port: 8282

spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        register: false
    loadbalancer:
      cache:
        ttl: 30s
      ribbon:
        enabled: false
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
