#logging.level.org.springframework.cloud.gateway.filter: trace

spring:
  application:
    name: dispatcher-modelArts-test
  cloud:
    gateway:
      routes:
        - id: test1
          uri: http://127.0.0.1:8443
          predicates:
            - Path=/test1/**
          filters:
            - StripPrefix=1
  codec:
    max-in-memory-size: 12MB
server:
  port: 8001
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG