server:
  port: 8282
logging:
  level:
    reactor:
      netty: DEBUG
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      cache:
        ttl: 30s
      ribbon:
        enabled: false
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - predicates:
            - Path=/foo
          uri: http://127.0.0.1:10001/foo
          filters:
            - name: Retry
              args:
                methods: GET