logging.level.org.springframework.cloud.gateway.filter: trace

server:
  port: 8282

spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        register: false
    loadbalancer:
      cache:
        ttl: 30s
    gateway:
      predicate:
        cloud-foundry-route-service:
          enabled: false
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - predicates:
            - Path=/foo
          uri: lb://foo
          filters:
            - name: Retry
              args:
                methods: GET