spring:
  application:
    name: foo
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
          ttl-unit: s
          ttl-value: 10
    loadbalancer:
      cache:
        ttl: 30s
      ribbon:
        enabled: false
